# Set your configuration here
config:
  AIRBREAK_AUTH_TOKEN: 75725a8332cdcd5b967c5defcb31adbecc210d46
  AIRBREAK_API_KEY: e5298dffad60e869e95e9b79171a1eaf
  AIRBREAK_SUBDOMAIN: diinostaging
  AIRBREAK_PROJECT_ID: 82348
  PIVOTAL_PROJECT_ID: 610859
  PIVOTAL_API_TOKEN: 914b74a111fa3ddd7e5f02ef0a499e38
  REQUESTER: 'Surat Pyari'
  AIRBREAK_PROJECT_URL: "diinostaging.airbrake.io"
  AIRBREAK_USERNAME: web+diino@sapnasolutions.com
  AIRBREAK_PASSWORD: web+diino